inherit_from: ../.rubocop.yml

# Offense count: 1
Metrics/AbcSize:
  Max: 16

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 22

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 8
