default: &default
  enabled: true
  repository:
    domain: ""
    endpoint: ""
    username: ""
    password: ""
  contact_email: ["contact1@example.edu", "contact2@example.edu"]
  abbreviation: "DataONE"
  short_name: "DataONE"
  long_name: "DataONE"
  full_domain: "localhost:3000"
  domain_regex: "localhost:3000$"
  tenant_id: dataone
  identifier_service:
    shoulder: "doi:10.5072/FK2"
    account:
    password:
    id_scheme: doi
    owner: null
  authentication:
    strategy: google
  default_license: cc0
  dash_logo_after_tenant: false
  max_file_size: 500000000
  max_submission_size: 10000000000
  max_total_version_size: 100000000000

development:
  <<: *default
  #Add any items that need to override the defaults here

test:
  <<: *default
  #Add any items that need to override the defaults here
