default: &default
  repository:
    type: merritt
    endpoint: "http://merritt-dev.cdlib.org/object/update"
    username: "ucb"
    password: ""
    profile: "dash_ucb_content"
  contact_email: ["contact1@contact.com", "contact2@contact.com"]
  abbreviation: "UCB"
  short_name: "UC Berkeley"
  long_name: "University of California, Berkeley"
  full_domain: "dash2-dev.cdlib.org"
  domain_regex: "dash2-dev.cdlib.org$"
  tenant_id: ucb
  logo: dash_ucb_logo.png
  identifier_service:
    shoulder: "doi:10.5072/FK2"
    account: apitest
    password: apitest
    id_scheme: doi
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:berkeley.edu
    entity_domain: .berkeley.edu

development:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production:
  <<: *default
  #Add any items that need to override the defaults here

test:
  <<: *default
  #Add any items that need to override the defaults here
