default: &default
  enabled: true
  repository:
    type: merritt
    domain: ""
    endpoint: ""
    username: ""
    password: ""
  contact_email: ["contact1@example.edu", "contact2@example.edu"]
  abbreviation: "UC"
  short_name: "UC Office of the President"
  long_name: "University of California, Office of the President"
  full_domain: "localhost:3000"
  domain_regex: "localhost:3000$"
  tenant_id: ucop
  identifier_service:
    shoulder: "doi:10.5072/FK2"
    account: ""
    password: ""
    id_scheme: doi
    owner: null
  authentication:
    strategy: shibboleth
    entity_id: ""
    entity_domain: ""
  default_license: cc_by
  dash_logo_after_tenant: true

development:
  <<: *default
  #Add any items that need to override the defaults here

test:
  <<: *default
  #Add any items that need to override the defaults here
