AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/dummy/db/**/*'
    - 'test/dummy/db/**/*'
    - 'vendor/**/*'
    - 'app/models/stash_datacite/resource/resource_file_generation.rb'
  # Suppress complaints about post-2.0 syntax
  TargetRubyVersion: 2.2

# documentation
Documentation:
  Exclude:
    - 'db/**/*'
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'test/controllers/**/*'
    - 'lib/stash_datacite/**/*'
    - 'lib/stash_datacite.rb'
    - 'spec/**/*'

# Reasonable line-length check; it's too easy for the cure to be worse than the disease
Metrics/LineLength:
  Max: 150

# Disable problematic module documentation check (see https://github.com/bbatsov/rubocop/issues/947)
Style/Documentation:
  Enabled: false

# Allow one line around class body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow one line around module body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow one line around block body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Unclear why it's a good idea to give parameters semantically meaningless names
Style/SingleLineBlockParams:
  Enabled: false
