inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/dummy/db/**/*'
    - 'test/dummy/db/**/*'
    - 'vendor/**/*'
  # Suppress complaints about post-2.0 syntax
  TargetRubyVersion: 2.2

# These files are just inherently long lists of things
Metrics/MethodLength:
  Exclude:
    - lib/stash_datacite/resource_patch.rb
    - lib/stash_datacite/author_patch.rb

# These files are just inherently long lists of things
Metrics/BlockLength:
  Exclude:
    - lib/stash_datacite/resource_patch.rb
    - lib/stash_datacite/author_patch.rb

# These files are just inherently long lists of things
Metrics/AbcSize:
  Exclude:
    - lib/stash_datacite/resource_patch.rb
    - lib/stash_datacite/author_patch.rb
