inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/dummy/db/**/*'
    - 'vendor/**/*'

# other configuration
Metrics/LineLength:
  Max: 120

# documentation
Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'test/controllers/**/*'
    - 'lib/stash_datacite/**/*'
    - 'lib/stash_datacite.rb'
    - 'test/**/*'

Style/LeadingCommentSpace:
  Enabled: false

