# Disable line-length check; it's too easy for the cure to be worse than the disease
Metrics/LineLength:
  Enabled: False

# Allow %r notation for regexes with a single / character
Style/RegexpLiteral:
  MaxSlashes: 0

# Disable problematic module documentation check (see https://github.com/bbatsov/rubocop/issues/947)
Style/Documentation:
  Enabled: false
