# inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/dummy/db/**/*'
    - 'vendor/**/*'
    - 'ui-library/**/*'
    - 'node_modules/**/*'

# other configuration
Metrics/LineLength:
  Max: 120

# Rubocop again acts like a school marm.  They made rules to disallow prepositions at the end of sentences because of
# Latin. English isn't Latin, so give it a rest.  Usage should be useful for expression, not stupidly prescriptive.
#
# While many small methods are ideal, often a small straight-forward chunk is perfectly reasonable and prevents
# ping-pong code involving jumping through many methods to see complete picture or debug something simple.
#
# It is also extremely stupid and disallows recommended conventions such as responding to format and multiple formats
# in a controller method.
Metrics/AbcSize:
  Max: 30

# Rubocop is really bad at counting method length since it counts things such as arrays or hashes with multiple
# values as a line each if you follow recommended practices of aligning on subsequent lines. Not impressed.
Metrics/MethodLength:
  Max: 30

# documentation
Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'app/models/**/*'
    - 'test/controllers/**/*'
    - 'lib/stash_engine/**/*'
    - 'lib/stash_engine.rb'
    - 'test/**/*'

Style/LeadingCommentSpace:
  Enabled: false

