language: ruby
services:
  - mysql
before_install:
  - gem update --system 2.6.8
  - git clone https://github.com/CDLUC3/stash_engine.git ../stash_engine
  - git clone https://github.com/CDLUC3/stash_discovery.git ../stash_discovery
before_script:
  - mysql -e 'create database stash_datacite_test;'
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test rails s
  - bundle exec rspec spec/features/metadata_entry_page_with_geo_spec.rb
  - bundle exec rspec spec/features/metadata_entry_page_with_incomplete_data_notification_spec.rb
  - bundle exec rspec spec/features/update_and_resubmit_dataset_spec.rb
branches:
  only:
    - development
notifications:
  email:
    on_success: change
    on_failure: always
#test commit for travis.
addons:
  sauce_connect: true