language: ruby
services:
  - mysql
before_install:
  - gem update --system 2.6.8
  - git clone https://github.com/CDLUC3/stash_engine.git ../stash_engine
  - git clone https://github.com/CDLUC3/stash_discovery.git ../stash_discovery
before_script:
  - mysql -e 'create database stash_datacite_test;'
  - RAILS_ENV=test bundle exec rake db:schema:load
script:
  - cd $TRAVIS_BUILD_DIR/spec/dummy
  - $echo PATH
branches:
  only:
    - development
notifications:
  email:
    on_success: change
    on_failure: always
#test commit for travis.
addons:
  sauce_connect: true