language: ruby
rvm:
  - 2.2.3
services:
  - mysql
before_script:
  - mysql -e 'create database stash_datacite_test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
  - bundle exec rubocop -R
branches:
  only:
    - development
#test commit for travis.