language: ruby
services:
  - mysql
before_script:
  - mysql -e 'create database stash_datacite_test;'
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec --color --format documentation --require spec_helper --require rails_helper
  - bundle exec rubocop -R
branches:
  only:
    - development
notifications:
  email:
    on_success: change
    on_failure: always
#test commit for travis.
env:
  global:
    - secure: "cdluc3"
    - secure: "4eb42a92-0fc6-43d5-9494-4d52a50a066f"
    - SAUCY: true

addons:
  sauce_connect: true