AllCops:
  # Suppress complaints about post-2.0 syntax
  TargetRubyVersion: 2.2

# Reasonable line-length check; it's too easy for the cure to be worse than the disease
Metrics/LineLength:
  Max: 150

# Disable problematic module documentation check (see https://github.com/bbatsov/rubocop/issues/947)
Style/Documentation:
  Enabled: false

# Allow one line around class body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow one line around module body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow one line around block body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Unclear why it's a good idea to give parameters semantically meaningless names
Style/SingleLineBlockParams:
  Enabled: false

# Make indents consistent regardless of the lengths of variables and method names and whatnot
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# These 'set' methods aren't conventional accessors, but Rubocop doesn't know that
Style/AccessorMethodName:
  Exclude:
    - 'spec/util/resource_builder.rb'
