# Reasonable line-length check; it's too easy for the cure to be worse than the disease
Metrics/LineLength:
  Max: 150

# Make indents consistent regardless of the lengths of variables and method names and whatnot
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
