inherit_from: ../.rubocop.yml

# RSpec tests are inevitably one big BlockLength violation
Metrics/BlockLength:
  Enabled: False

# These 'set' methods aren't conventional accessors, but Rubocop doesn't know that
Style/AccessorMethodName:
  Exclude:
    - 'spec/util/resource_builder.rb'
