development:
  adapter: sqlite3
  database: model/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: model/production.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: model/test.sqlite3
  pool: 5
  timeout: 5000
