cc0:
  uri: https://creativecommons.org/publicdomain/zero/1.0/
  name: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
  explanation: >
    This releases your work to the public domain for any use.
  badge: icon_cc-zero.svg
