name: RSpec Internal Tests

on: [push, pull_request]

jobs:
  setup:
    name: Dryad setup
    runs-on: ubuntu-latest

    env:
      DB_ADAPTER: mysql2
      MYSQL_PWD: root
      RAILS_ENV: test

    steps:
    - name: 'Checkout the repo'
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: 'Install MySQL Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client libmysqlclient-dev

    - name: 'Set Ruby and Bundler Versions'
      run: |
        echo "RUBY_VERSION=2.6.6" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    - name: 'Install Ruby'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    - name: 'Retrieve Cached Gems'
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: 'Bundle Install'
      run: |
        gem install bundler -v ${{ env.BUNDLER_VERSION }}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --without pgsql rollbar aws

    - name: 'Start MySQL'
      run: sudo systemctl start mysql

    - name: 'Setup Test DB'
      run: |
        mysql -u root -e 'CREATE DATABASE IF NOT EXISTS dryad_test' 
        bin/rails db:migrate RAILS_ENV=test
        bin/rails db:setup RAILS_ENV=test

  rspec-internal:
    name: RSpec Internal Tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: 'Run RSpec Internal Tests'
      run: |
        bin/bundle exec rspec spec/controllers
        bin/bundle exec rspec spec/jobs
        bin/bundle exec rspec spec/models
        bin/bundle exec rspec spec/services
        bin/bundle exec rspec spec/tasks

  rubocop:
    name: Rubocop
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: 'Run Rubocop'
      run: bin/rubocop
