name: RSpec Tests

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      DB_ADAPTER: mysql2
      MYSQL_PWD: root
      RAILS_ENV: test

    steps:
    # Checkout the repo
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: 'Install MySQL Packages'
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client libmysqlclient-dev

    - name: 'Determine Ruby and Bundler Versions from Gemfile.lock'
      run: |
        echo "RUBY_VERSION=2.6.6" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    - name: 'Install Ruby'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

#    # Copy all of the example configs over
#    - name: 'Setup Default Configuration'
#      run: |
#        # Make copies of all the example config files
#        cp config/database.yml.sample config/database.yml
#        cp config/initializers/contact_us.rb.example config/initializers/contact_us.rb
#        cp config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb

    # Try to retrieve the gems from the cache
    - name: 'Cache Gems'
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: 'Bundle Install'
      run: |
        gem install bundler -v ${{ env.BUNDLER_VERSION }}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --without pgsql rollbar aws

#    - name: 'Setup Credentials'
#      run: |
#        # generate a default credential file and key
#        EDITOR='echo "$(cat config/credentials.yml.example)" >' bundle exec rails credentials:edit

    - name: 'Start MySQL'
      run: sudo systemctl start mysql

    - name: 'Setup Test DB'
      # mysql -u root -e 'GRANT ALL ON dashv2_test.* TO travis@localhost'
      run: |
        mysql -u root -e 'CREATE DATABASE IF NOT EXISTS dryad_test' 
        bin/rails db:migrate RAILS_ENV=test
        bin/rails db:setup RAILS_ENV=test

    - name: 'Compile Assets'
      run: |
#        bin/rails webpacker:compile
        bin/rails assets:precompile

    - name: 'Run RSpec Tests'
      run: bin/bundle exec rspec RAILS_ENV=test
