name: RSpec -- Simple version

on: [push, pull_request]

jobs:
  rspec-simple:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Determine Ruby and Bundler Versions from Gemfile.lock'
      run: |
        echo "RUBY_VERSION=2.6.6" >> $GITHUB_ENV
        echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV

    - name: 'Install Ruby'
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}

    - name: 'Bundle Install'
      run: |
        gem install bundler -v ${{ env.BUNDLER_VERSION }}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --without pgsql rollbar aws

    - name: 'Run Rubocop'
      run: RAILS_ENV=test bundle exec rspec
