name: Travis

on: push

jobs:
  travis:
    name: Travis Script Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run .travis.yml build script
        uses: ktomk/run-travis-yml@v1
        with:
          file: .travis.yml
          steps: |
            install
            script
          allow-failure: false
        env:
          TRAVIS_PHP_VERSION: ${{ matrix.php-versions }}
