inherit_from: ../.rubocop.yml

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/dummy/db/**/*'
    - 'test/dummy/db/**/*'
    - 'vendor/**/*'
    - 'ui-library/**/*'
    - 'node_modules/**/*'
  # Suppress complaints about post-2.0 syntax
  TargetRubyVersion: 2.2
